### ISSUE TITLE
Error in creating VGG weights python27

### ISSUE THREAD

**Issue by ImmanuelSamuel** [abbypa/NNProject_DeepMask#14]
`python CreateVggGraphWeights.py` results in following error

```
Traceback (most recent call last):
  File "CreateVggGraphWeights.py", line 144, in <module>
    graph = VGG_16_graph()
  File "CreateVggGraphWeights.py", line 99, in VGG_16_graph
    model.add_node(Flatten(), name='27', input='26')
  File "/home/immanuel/programs/python2-packages/keras/keras/legacy/models.py", line 169, in add_node
    layer.add_inbound_node(self._graph_nodes[input])
  File "/home/immanuel/programs/python2-packages/keras/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/immanuel/programs/python2-packages/keras/keras/engine/topology.py", line 152, in create_node
    output_shapes = to_list(outbound_layer.get_output_shape_for(input_shapes[0]))
  File "/home/immanuel/programs/python2-packages/keras/keras/layers/core.py", line 402, in get_output_shape_for
    '(got ' + str(input_shape[1:]) + '. '
Exception: The shape of the input to "Flatten" is not fully defined (got (0, 7, 512). Make sure to pass a complete "input_shape" or "batch_input_shape" argument to the first layer in your model.
```

**Comment by ImmanuelSamuel** [comment]
The above error was with git version of keras

The following error occurs after uninstalling keras followed by pip install -I keras=0.3.1
```
Traceback (most recent call last):
  File "CreateVggGraphWeights.py", line 1, in <module>
    from keras.models import *
  File "/home/immanuel/programs/anaconda3/envs/py27/lib/python2.7/site-packages/keras/models.py", line 15, in <module>
    from . import backend as K
  File "/home/immanuel/programs/anaconda3/envs/py27/lib/python2.7/site-packages/keras/backend/__init__.py", line 45, in <module>
    from .theano_backend import *
  File "/home/immanuel/programs/anaconda3/envs/py27/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 4, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name downsample
```

**Comment by ImmanuelSamuel** [comment]
Downgrading keras 0.3.1fixed it.
