### ISSUE TITLE
Unable to open object (Object 'graph' doesn't exist)

### ISSUE THREAD

**Issue by slavakurilyak** [abbypa/NNProject_DeepMask#15]
I'm getting error - `Unable to open object (Object 'graph' doesn't exist)`

```
$ python EndToEnd.py
Using Theano backend.
/usr/local/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
2016-10-14 12:53:30.489447: creating net...
Traceback (most recent call last):
  File "EndToEnd.py", line 208, in <module>
    main()
  File "EndToEnd.py", line 172, in main
    graph = create_net()
  File "EndToEnd.py", line 101, in create_net
    net = net_generator.create_full_net()
  File "/Users/skurilyak/Documents/dev/testing/abbypa/NNProject_DeepMask/FullNetGenerator.py", line 12, in create_full_net
    net = vgg_provider.get_vgg_partial_graph(weights_path=self.weights_path, with_output=False)
  File "/Users/skurilyak/Documents/dev/testing/abbypa/NNProject_DeepMask/VggDNetGraphProvider.py", line 60, in get_vgg_partial_graph
    model = self.get_vgg_full_graph(weights_path, False)
  File "/Users/skurilyak/Documents/dev/testing/abbypa/NNProject_DeepMask/VggDNetGraphProvider.py", line 56, in get_vgg_full_graph
    model.load_weights(weights_path)
  File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 1230, in load_weights
    g = f['graph']
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2687)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2645)
  File "/usr/local/lib/python2.7/site-packages/h5py/_hl/group.py", line 166, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2687)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2645)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/h5o.c:3573)
KeyError: "Unable to open object (Object 'graph' doesn't exist)"
```

Any ideas? 

Maybe it's related to keras issue - [loading weights of a sequential model into a graph model](https://github.com/fchollet/keras/issues/1728)?

**Comment by abbypa** [comment]
Are you using the Keras version written in the readme file?
Previous errors regarding the 'Graph' object were fixed by using the correct version.

**Comment by slavakurilyak** [comment]
Yes, I'm using Keras 0.3.1

```
$ pip show keras
---
Metadata-Version: 2.0
Name: Keras
Version: 0.3.1
Summary: Theano-based Deep Learning library
Home-page: https://github.com/fchollet/keras
Author: Francois Chollet
Author-email: francois.chollet@gmail.com
Installer: pip
License: MIT
Location: /usr/local/lib/python2.7/site-packages
Requires: theano, pyyaml, six
Classifiers:
```

**Comment by abbypa** [comment]
Seems like the weights file you provided is illegal.
Did you download and convert graph weights with HeplerScripts/CreateVggGraphWeights.py?

**Comment by slavakurilyak** [comment]
I re-downloaded the net and got another error:

```
$ python EndToEnd.py
Using Theano backend.
/usr/local/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
2016-10-19 15:08:45.333989: loading net...
2016-10-19 15:08:48.983922: compiling net...
2016-10-19 15:09:02.794350: preparing data...
Traceback (most recent call last):
  File "EndToEnd.py", line 208, in <module>
    main()
  File "EndToEnd.py", line 178, in main
    train_images, train_expected_scores, train_expected_masks = prepare_data(train_images_path)
  File "EndToEnd.py", line 136, in prepare_data
    images = prepare_local_images(ex_paths)
  File "/Users/skurilyak/Documents/dev/testing/abbypa/NNProject_DeepMask/ImageUtils.py", line 10, in prepare_local_images
    return np.stack(prepared_imgs)
  File "/usr/local/lib/python2.7/site-packages/numpy/core/shape_base.py", line 335, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```

Any ideas?

**Comment by abbypa** [comment]
Did you create the learning dataset using ExamplesGenerator.py?
