### ISSUE TITLE
CreateVggGraphWeights.py error （not graph error）

### ISSUE THREAD

**Issue by brisker** [abbypa/NNProject_DeepMask#17]
"downsample module has been moved to the theano.tensor.signal.pool module.")
creating graph model...
creating sequential model...
Traceback (most recent call last):
  File "CreateVggGraphWeights.py", line 147, in <module>
    model = VGG_16('..\Resources\vgg16_weights.h5')
  File "CreateVggGraphWeights.py", line 55, in VGG_16
    model.load_weights(weights_path)
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 781, in load_weights
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2582)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2541)
  File "/home/sjtu/anaconda2/lib/python2.7/site-packages/h5py/_hl/attrs.py", line 58, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2582)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2541)
  File "h5py/h5a.pyx", line 77, in h5py.h5a.open (-------src-dir-------/h5py/h5a.c:2086)
KeyError: "Can't open attribute (Can't locate attribute: 'nb_layers')"

**Comment by abbypa** [comment]
What version of Keras did you use? Usually, when there's a missing attribute error of keras, it's a mismatch of versions issue.
