### ISSUE TITLE
can not load weights for graph 

### ISSUE THREAD

**Issue by ouceduxzk** [abbypa/NNProject_DeepMask#3]
Try to run python HelperScripts/CreateVggGraphWeights.py
Got error:
Traceback (most recent call last):
  File "HelperScripts/CreateVggGraphWeights.py", line 150, in <module>
    graph.set_weights(model.get_weights())
  File "/users/zaikun/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 841, in set_weights
    params = self.trainable_weights + self.non_trainable_weights
  File "/users/zaikun/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 1840, in trainable_weights
    for layer in self.layers:

**Comment by abbypa** [comment]
My call-tree seems different than yours- what version of keras are you using?

You can try to either get the specific version I used (see readme file, might be relevant to other steps later on) or write your own code to copy the weights layer by layer from the model to the graph.

Please update if any of these worked for you.

**Comment by zhengxuyu** [comment]
I got the Same error, how could I get the keras version(0.3.1) on a win-64bit ?

**Comment by zhengxuyu** [comment]
Hi guys, I solved this error, it's because the version of Keras, install the right version(0.3.1) will be ok
